spring.application.name=bookingsproject
spring.datasource.url = jdbc:mysql://localhost/bookingdb
spring.datasource.username = root
spring.datasource.password = 
spring.servlet.multipart.max-file-size=100MB
spring.servlet.multipart.max-request-size=200MB
server.tomcat.max-swallow-size=200MB
paypal.client-id=AZXRizM70V1wpgKR28S3VtICe_1u9tPrqLQFKffr27dOn9GZBDzhBD8De8RFBW6lDJS7ksh8O8z1jCT9
paypal.client-secret=ELbxO33ymOl52iXpP04yAlEDM5lQ-HGeV2-ShLlTV0kIAlxKA66kjqRxw--DelCGAyBZLMGeAtW1a5JR
paypal.base-url=https://api-m.sandbox.paypal.com
paypal.currency=EUR
paypal.rsd-to-eur-rate=117
paypal.hold-minutes=10